export const GENERAL_LOADER_REDUX_CONSTANTS = {
  START_GENERAL_LOADER_ON_REQUEST: 'START_GENERAL_LOADER_ON_REQUEST',
  STOP_GENERAL_LOADER_ON_SUCCESS_OR_FAIL: 'STOP_GENERAL_LOADER_ON_SUCCESS_OR_FAIL',
  // STOP_LOADER_BUTTON_ON_FAIL: 'STOP_LOADER_BUTTON_ON_FAIL',
};
