export const CLAIMS_REDUX_CONSTANTS = {
  CLAIMS_LIST_REQUEST: 'CLAIMS_LIST_REQUEST',
  CLAIMS_LIST_SUCCESS: 'CLAIMS_LIST_SUCCESS',
  CLAIMS_LIST_FAILURE: 'CLAIMS_LIST_FAILURE',

  GET_CLAIMS_COLUMNS_LIST: 'GET_CLAIMS_COLUMNS_LIST',
  GET_CLAIMS_DEFAULT_COLUMN_LIST: 'GET_CLAIMS_DEFAULT_COLUMN_LIST',
  UPDATE_CLAIMS_COLUMNS_LIST: 'UPDATE_CLAIMS_COLUMNS_LIST',
};
