export const CLAIMS_REDUX_CONSTANTS = {
  CLAIMS_LIST_REQUEST: 'CLAIMS_LIST_REQUEST',
  CLAIMS_LIST_SUCCESS: 'CLAIMS_LIST_SUCCESS',
  CLAIMS_LIST_FAILURE: 'CLAIMS_LIST_FAILURE',

  GET_CLAIMS_COLUMNS_LIST: 'GET_CLAIMS_COLUMNS_LIST',
  GET_CLAIMS_DEFAULT_COLUMN_LIST: 'GET_CLAIMS_DEFAULT_COLUMN_LIST',
  UPDATE_CLAIMS_COLUMNS_LIST: 'UPDATE_CLAIMS_COLUMNS_LIST',

  GET_CLAIMS_ENTITY_LIST: 'GET_CLAIMS_ENTITY_LIST',

  ADD_CLAIMS_VALUE_CHANGE: 'ADD_CLAIMS_VALUE_CHANGE',
  GET_CLAIM_DETAILS: 'GET_CLAIM_DETAILS',
  RESET_CLAIMS_DETAILS: 'RESET_CLAIMS_DETAILS',
};
