export const EDIT_PROFILE_CONSTANT = {
  GET_LOGGED_USER_DETAILS: 'GET_LOGGED_USER_DETAILS',
  USER_EDIT_PROFILE_DATA_CHANGE: 'USER_EDIT_PROFILE_DATA_CHANGE',
  UPDATE_USER_PROFILE_PICTURE: 'UPDATE_USER_PROFILE_PICTURE',
};
