export const REIMBURSEMENT_REQUESTED = [
  { label: 'Info from Client', value: 'Info from Client', name: 'reimbursementrequested' },
  {
    label: 'Payment from Underwriter',
    value: 'Payment from Underwriter',
    name: 'reimbursementrequested',
  },
];

export const POD_RECEIVED = [
  { label: 'Completed by TCR', value: 'Completed by TCR', name: 'podreceived' },
  { label: 'Completed by Client', value: 'Completed by Client', name: 'podreceived' },
];

export const DL_JUSTIFICATION = [
  { label: 'Endorsed Limit', value: 'Endorsed Limit', name: 'dljustification' },
  { label: 'Mercantile Report', value: 'Mercantile Report', name: 'dljustification' },
  { label: 'Monitored Account', value: 'Monitored Account', name: 'dljustification' },
  { label: 'Rescheck', value: 'Rescheck', name: 'dljustification' },
  { label: 'Trading History', value: 'Trading History', name: 'dljustification' },
];

export const UNDERWRITER = [
  { label: 'Atradius', value: 'Atradius', name: 'underwriter' },
  { label: 'Bond & Credit Co', value: 'Bond & Credit Co', name: 'underwriter' },
  { label: 'Coface Australia', value: 'Coface Australia', name: 'underwriter' },
  { label: 'Euler Hermes', value: 'Euler Hermes', name: 'underwriter' },
  { label: 'QBE Trade Credit', value: 'QBE Trade Credit', name: 'underwriter' },
  { label: 'Trade Credit Risk', value: 'Trade Credit Risk', name: 'underwriter' },
];

export const STAGE = [
  { label: 'Approved - In Full', value: 'Approved - In Full', name: 'stage' },
  { label: 'Approved - Partial', value: 'Approved - Partial', name: 'stage' },
  { label: 'Collection Only', value: 'Collection Only', name: 'stage' },
  { label: 'Closed Debtor Paid', value: 'Closed Debtor Paid', name: 'stage' },
  { label: 'Declined', value: 'Declined', name: 'stage' },
  { label: 'Pending Collection', value: 'Pending Collection', name: 'stage' },
  { label: 'Pending Claim', value: 'Pending Claim', name: 'stage' },
  { label: 'Pending Repayment Plan', value: 'Pending Repayment Plan', name: 'stage' },
  { label: 'Bad Debt Pre Insurance', value: 'Bad Debt Pre Insurance', name: 'stage' },
  {
    label: 'Approved - In Full/ Preference Claim Pending',
    value: 'Approved - In Full/ Preference Claim Pending',
    name: 'stage',
  },
  {
    label: 'Approved - In Full/ Preference Claim Approved - In Full',
    value: 'Approved - In Full/ Preference Claim Approved - In Full',
    name: 'stage',
  },
  {
    label: 'Approved - In Full/ Preference Claim Approved - In Partial',
    value: 'Approved - In Full/ Preference Claim Approved - In Partial',
    name: 'stage',
  },
  {
    label: 'Approved - In Full/ Preference Claim Declined',
    value: 'Approved - In Full/ Preference Claim Declined',
    name: 'stage',
  },
  {
    label: 'Approved - Partial/ Preference Claim Pending',
    value: 'Approved - Partial/ Preference Claim Pending',
    name: 'stage',
  },
  {
    label: 'Approved - Partial/ Preference Claim Approved - In Full',
    value: 'Approved - Partial/ Preference Claim Approved - In Full',
    name: 'stage',
  },
  {
    label: 'Approved - Partial/ Preference Claim Approved - In Partial',
    value: 'Approved - Partial/ Preference Claim Approved - In Partial',
    name: 'stage',
  },
  {
    label: 'Approved - Partial/ Preference Claim Declined',
    value: 'Approved - Partial/ Preference Claim Declined',
    name: 'stage',
  },
];

export const SECTOR = [
  { label: 'Accounting', value: 'Accounting', name: 'sector' },
  { label: 'Advertising', value: 'Advertising', name: 'sector' },
  { label: 'Aerospace', value: 'Aerospace', name: 'sector' },
  { label: 'Agriculture', value: 'Agriculture', name: 'sector' },
  { label: 'Apparel', value: 'Apparel', name: 'sector' },
  { label: 'Automotive', value: 'Automotive', name: 'sector' },
  { label: 'Banking', value: 'Banking', name: 'sector' },
  { label: 'Biotechnology', value: 'Biotechnology', name: 'sector' },
  { label: 'Chemicals', value: 'Chemicals', name: 'sector' },
  { label: 'Communications', value: 'Communications', name: 'sector' },
  { label: 'Construction', value: 'Construction', name: 'sector' },
  { label: 'Consulting', value: 'Consulting', name: 'sector' },
  { label: 'Design', value: 'Design', name: 'sector' },
  { label: 'Distribution', value: 'Distribution', name: 'sector' },
  { label: 'Education', value: 'Education', name: 'sector' },
  { label: 'Electronics', value: 'Electronics', name: 'sector' },
  { label: 'Energy', value: 'Energy', name: 'sector' },
  { label: 'Engineering', value: 'Engineering', name: 'sector' },
  { label: 'Environmental', value: 'Environmental', name: 'sector' },
  { label: 'Facilities Management', value: 'Facilities Management', name: 'sector' },
  { label: 'Finance', value: 'Finance', name: 'sector' },
  { label: 'Food & Beverage', value: 'Food & Beverage', name: 'sector' },
  { label: 'Gaming', value: 'Gaming', name: 'sector' },
  { label: 'Gardening', value: 'Gardening', name: 'sector' },
  { label: 'Government', value: 'Government', name: 'sector' },
  { label: 'Healthcare', value: 'Healthcare', name: 'sector' },
  { label: 'Hospitality', value: 'Hospitality', name: 'sector' },
  { label: 'Insurance', value: 'Insurance', name: 'sector' },
  { label: 'IT', value: 'IT', name: 'sector' },
  { label: 'Legal', value: 'Legal', name: 'sector' },
  { label: 'Leisure', value: 'Leisure', name: 'sector' },
  { label: 'Logistics', value: 'Logistics', name: 'sector' },
  { label: 'Machinery', value: 'Machinery', name: 'sector' },
  { label: 'Manufacturing', value: 'Manufacturing', name: 'sector' },
  { label: 'Marketing', value: 'Marketing', name: 'sector' },
  { label: 'Media & Entertainment', value: 'Media & Entertainment', name: 'sector' },
  { label: 'Mining', value: 'Mining', name: 'sector' },
  { label: 'Not For Profit', value: 'Not For Profit', name: 'sector' },
  { label: 'Office Supplies', value: 'Office Supplies', name: 'sector' },
  { label: 'Other', value: 'Other', name: 'sector' },
  { label: 'Packaging', value: 'Packaging', name: 'sector' },
  { label: 'Pharma', value: 'Pharma', name: 'sector' },
  { label: 'Photography', value: 'Photography', name: 'sector' },
  { label: 'Print', value: 'Print', name: 'sector' },
  { label: 'Property', value: 'Property', name: 'sector' },
  { label: 'Publishing', value: 'Publishing', name: 'sector' },
  { label: 'Recreation', value: 'Recreation', name: 'sector' },
  { label: 'Recruitment', value: 'Recruitment', name: 'sector' },
  { label: 'Research', value: 'Research', name: 'sector' },
  { label: 'Retail', value: 'Retail', name: 'sector' },
  { label: 'Service', value: 'Service', name: 'sector' },
  { label: 'Shipping', value: 'Shipping', name: 'sector' },
  { label: 'Technology', value: 'Technology', name: 'sector' },
  { label: 'Telecoms', value: 'Telecoms', name: 'sector' },
  { label: 'Tobacco', value: 'Tobacco', name: 'sector' },
  { label: 'Training', value: 'Training', name: 'sector' },
  { label: 'Transportation', value: 'Transportation', name: 'sector' },
  { label: 'Travel', value: 'Travel', name: 'sector' },
  { label: 'Unknown', value: 'Unknown', name: 'sector' },
  { label: 'Utilities', value: 'Utilities', name: 'sector' },
  { label: 'Wholesale', value: 'Wholesale', name: 'sector' },
];
