export const CLIENT_REDUX_CONSTANTS = {
  CLIENT_DATA: 'CLIENT_DATA',
  CLIENT_POLICY_DATA: 'CLIENT_POLICY_DATA',
  CLIENT_POLICY_COLUMN_LIST: 'CLIENT_POLICY_COLUMN_LIST',
  CLIENT_POLICY_DEFAULT_COLUMN_LIST: 'CLIENT_POLICY_DEFAULT_COLUMN_LIST',
  CLIENT_POLICY_UPDATE_COLUMN_LIST: 'CLIENT_POLICY_UPDATE_COLUMN_LIST',
  RESET_CLIENT_DATA: 'RESET_CLIENT_DATA',
};
