export const DASHBOARD_REDUX_CONSTANTS = {
  TASK: {
    DASHBOARD_TASK_LIST_REQUEST: 'DASHBOARD_TASK_LIST_REQUEST',
    DASHBOARD_TASK_LIST_SUCCESS: 'DASHBOARD_TASK_LIST_SUCCESS',
  },
  NOTIFICATION: {
    DASHBOARD_NOTIFICATION_LIST_REQUEST: 'DASHBOARD_NOTIFICATION_LIST_REQUEST',
    DASHBOARD_NOTIFICATION_LIST_SUCCESS: 'DASHBOARD_NOTIFICATION_LIST_SUCCESS',
  },
};
