export const CREDIT_LIMITS_REDUX_CONSTANTS = {
  CREDIT_LIMITS_LIST_USER_ACTION: 'CREDIT_LIMITS_LIST_USER_ACTION',
  SELECTED_CREDIT_LIMIT_DATA: 'SELECTED_CREDIT_LIMIT_DATA',
};
export const CREDIT_LIMITS_COLUMN_LIST_REDUX_CONSTANTS = {
  CREDIT_LIMITS_COLUMN_LIST_ACTION: 'CREDIT_LIMITS_COLUMN_LIST_ACTION',
  UPDATE_CREDIT_LIMITS_COLUMN_LIST_ACTION: 'UPDATE_CREDIT_LIMITS_COLUMN_LIST_ACTION',
};
