export const LOADER_BUTTON_REDUX_CONSTANTS = {
  START_LOADER_BUTTON_ON_REQUEST: 'START_LOADER_BUTTON_ON_REQUEST',
  STOP_LOADER_BUTTON_ON_SUCCESS_OR_FAIL: 'STOP_LOADER_BUTTON_ON_SUCCESS_OR_FAIL',
  // STOP_LOADER_BUTTON_ON_FAIL: 'STOP_LOADER_BUTTON_ON_FAIL',
};
