export const OVERDUE_REDUX_CONSTANTS = {
  GET_OVERDUE_LIST: 'GET_OVERDUE_LIST',
  GET_ENTITY_LIST: 'GET_ENTITY_LIST',
  OVERDUE_CRUD_CONSTANTS: {
    UPDATE_OVERDUE_LIST_AFTER_AMEND: 'UPDATE_OVERDUE_LIST_AFTER_AMEND',
    UPDATE_OVERDUE_LIST_AFTER_ADD: 'UPDATE_OVERDUE_LIST_AFTER_ADD',
    CHANGE_OVERDUE_DETAILS_ACTION: 'CHANGE_OVERDUE_DETAILS_ACTION',
    GET_OVERDUE_DETAILS: 'GET_OVERDUE_DETAILS',
    GET_OVERDUE_LIST_BY_DATE: 'GET_OVERDUE_LIST_BY_DATE',
    CHANGE_OVERDUE_FIELD_VALUE: 'CHANGE_OVERDUE_FIELD_VALUE',
    RESET_OVERDUE_FORM_DATA: 'RESET_OVERDUE_FORM_DATA',
  },
};
